#!/bin/bash

# script_1 - Un script que informa algunos datos del sistema

##### Constantes

TITLE="Información del sistema para $HOSTNAME"

RIGHT_NOW=$(date +"%x %r%Z")
TIME_STAMP="Actualizada el $RIGHT_NOW por $USER"


##### Estilos
TEXT_BOLD=$(tput bold)
TEXT_ULINE=$(tput smul)

##### Colores
TEXT_RED=$(tput setaf 1)
TEXT_GREEN=$(tput setaf 2)
TEXT_YELLOW=$(tput setaf 3)
TEXT_BLUE=$(tput setaf 4)

##### Reset Text
TEXT_RESET=$(tput sgr0)

##### Funciones


system_info()
{
   echo "${TEXT_ULINE}${TEXT_BOLD}${TEXT_RED}Versión del sistema${TEXT_RESET}"
   uname -a
   echo
   return 0
}


show_uptime()
{
   echo "${TEXT_ULINE}${TEXT_BOLD}${TEXT_YELLOW}Tiempo de encendido del sistema$TEXT_RESET"
   uptime
   echo
   return 0
}


drive_space()
{
   echo "${TEXT_ULINE}${TEXT_BOLD}${TEXT_GREEN}Espacio ocupado por los discos$TEXT_RESET"
   df
   echo
   return 0
}


home_space()
{
   echo "${TEXT_ULINE}${TEXT_BOLD}${TEXT_BLUE}Espacio ocupado por cada uno de los subdirectorios$TEXT_RESET"
   if  [ "$USER" != root ]; then
      echo "${TEXT_BOLD}${TEXT_RED}ERROR: No tienes permisos de Superusuario! :($TEXT_RESET"
      return 1
   fi
   du -sh /home/*/
   return 0
}

##### Programa principal

cat << _EOF_

$TEXT_BOLD$TITLE$TEXT_RESET


$TEXT_GREEN$TIME_STAMP$TEXT_RESET

_EOF_

system_info
show_uptime
drive_space
home_space

exit 0